const content = {
  uz: {
    logo_title: 'ТДАУ',
    logo_info: ' Тошкент Давлат Аграр Универститети',
    login_title: 'Кириш',
    lang_ru: 'Рус тили',
    lang_uz: 'У`збек тили',
    e_username: 'Бу ерга фойдаланувчи номингизни киритинг',
    e_password: 'Бу ерга паролингизни киритинг',
    show_password: 'Паролни ку`рсатиш',
    date: 'Сана',
    date_from: 'Бошланиш санаси',
    date_to: 'Тугаш санаси',
    category: 'Категория',
    type: 'Мурожат тури',
    t_all: 'Барчаси',
    t_success: 'Таклиф',
    t_warning: 'Эътироз',
    t_danger: 'Шикоят',
    btn_send: 'Юбориш',
    btn_more: 'Батафсил',
    filter: 'Филтер',
    full_info: 'Барча маълумот',
    cancel: 'Бекор килиш',
  },

  ru: {
    logo_title: 'ТГАУ',
    logo_info: 'Ташкентский Государственный Аграрный Университет',
    login_title: 'Вход',
    lang_ru: 'Русский',
    lang_uz: 'Узбекский',
    e_username: 'Введите здесь ваше имя пользователя',
    e_password: 'Введите здесь свой пароль',
    show_password: 'Показать пароль',
    date: 'Дата',
    date_from: 'Дата c',
    date_to: 'Дата до',
    category: 'Категория',
    type: 'Тип',
    t_all: 'Все',
    t_success: 'Предложение',
    t_warning: 'Жалоба',
    t_danger: 'Возражение',
    btn_send: 'Отправлять',
    btn_more: 'Читать далее',
    filter: 'Филтер',
    full_info: 'Все информация',
    cancel: 'Отмена',
  },
};

export default content;
